import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { BloodTestReport } from '../types.ts';

export const generateBloodReportPdf = (report: BloodTestReport) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(37, 99, 235); // brand-blue
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('MEDIVISION AI', 20, 25);
  
  doc.setFontSize(10);
  doc.text('BLOOD TEST ANALYSIS REPORT', 20, 32);

  // Patient Info
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(12);
  doc.text(`Patient: ${report.patientName}`, 20, 55);
  doc.text(`Date: ${report.date}`, 20, 62);
  doc.text(`Report ID: ${report.id}`, pageWidth - 20, 55, { align: 'right' });

  // Results Table
  const tableData = report.results.map(res => [
    res.test,
    `${res.value} ${res.unit}`,
    `${res.refLow || '-'} - ${res.refHigh || '-'}`,
    res.status,
    res.interpretation || ''
  ]);

  (doc as any).autoTable({
    startY: 75,
    head: [['Test', 'Value', 'Reference Range', 'Status', 'AI Interpretation']],
    body: tableData,
    headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    margin: { left: 20, right: 20 },
    styles: { fontSize: 9, cellPadding: 5 },
    columnStyles: {
      3: { fontStyle: 'bold' }
    },
    didParseCell: (data: any) => {
      if (data.section === 'body' && data.column.index === 3) {
        const val = data.cell.raw;
        if (val === 'High' || val === 'Low') data.cell.styles.textColor = [217, 119, 6]; // amber
        if (val === 'Critical') data.cell.styles.textColor = [225, 29, 72]; // rose
        if (val === 'Normal') data.cell.styles.textColor = [5, 150, 105]; // emerald
      }
    }
  });

  const finalY = (doc as any).lastAutoTable.finalY || 150;

  // AI Insights
  let currentY = finalY + 20;
  if (report.aiInsights.length > 0) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('AI CLINICAL INSIGHTS', 20, currentY);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    currentY += 10;
    report.aiInsights.forEach(insight => {
      const lines = doc.splitTextToSize(`• ${insight}`, pageWidth - 40);
      doc.text(lines, 20, currentY);
      currentY += lines.length * 5 + 2;
    });
  }

  // Medication Conflicts
  if (report.medicationConflicts.length > 0) {
    currentY += 10;
    doc.setTextColor(225, 29, 72); // rose
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('MEDICATION CONFLICT ALERTS', 20, currentY);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    currentY += 10;
    report.medicationConflicts.forEach(conflict => {
      const lines = doc.splitTextToSize(`• ${conflict}`, pageWidth - 40);
      doc.text(lines, 20, currentY);
      currentY += lines.length * 5 + 2;
    });
  }

  // Disclaimer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  const disclaimer = "DISCLAIMER: This report is generated by AI for informational purposes only and does not constitute a medical diagnosis. Please consult a licensed healthcare professional for clinical interpretation.";
  const splitDisclaimer = doc.splitTextToSize(disclaimer, pageWidth - 40);
  doc.text(splitDisclaimer, 20, doc.internal.pageSize.getHeight() - 20);

  doc.save(`BloodTest_${report.patientName}_${report.date}.pdf`);
};
